### ISSUE TITLE
Build error with latest version of flutter

### ISSUE THREAD

**Issue by jijilpk** [luis901101/oauth_webauth#11]
Hi Luis,
Please check on compatibility with latest version of flutter stable version.  I have to downgrade the latest stable version of flutter to make it work

**Comment by luis901101** [comment]
Hi.
I will soon, I use this plugin in several projects… I was just waiting a bit for latest flutter release to spread so more third party plugins add support.

**Comment by frederikstonge** [comment]
I've created a pull request for this #12

**Comment by luis901101** [comment]
I just released: [v4.0.1+2](https://pub.dev/packages/oauth_webauth/versions/4.0.1+2)
