### ISSUE TITLE
Passing custom headers in request

### ISSUE THREAD

**Issue by jijilpk** [luis901101/oauth_webauth#2]
I have one question on how to pass headers  like Accept: application/json  with this package
For Eg for Github apps  by default it send response in url encoded format. We need to pass headers to get in other format like JSON. So I am getting format exception with this package. Could you please help me.

Ref Link: https://docs.github.com/en/developers/apps/building-oauth-apps/authorizing-oauth-apps#web-application-flow

**Comment by luis901101** [comment]
Hi, thanks for reporting this.  Not currently available to set request headers. I’ll add it in the next release.

**Comment by pkjijil** [comment]
ok

**Comment by luis901101** [comment]
Check [v2.2.0+9](https://pub.dev/packages/oauth_webauth/versions/2.2.0+9)
