### ISSUE TITLE
Discovery | Sys Browser Auto-fill

### ISSUE THREAD

**Issue by Yodart** [luis901101/oauth_webauth#3]
I have this package implemented on my application and it seems like the auto-complete/auto-fill feature present on the default system browser doesnt work here for now which is suboptimal given that nowadays people rely heavily com having there phones auto-complete there passwords, are there places to integrate this?

Congrats !

**Comment by luis901101** [comment]
Nop, this uses a webview implementation which has no access to the default browser cache or passwords. The webview manages its own cache. It is like when you use Chrome as your main default browser and then you use Firefox, you will not have autocomplete of anything. Nevertheless it integrates fine with common password managers like 1Password, Bitwarden, Keychain, etc.
