### ISSUE TITLE
Inline View

### ISSUE THREAD

**Issue by jijilpk** [luis901101/oauth_webauth#5]
In one of the main features it says full control over the UI, WebView will run inside your app. It means this will support displaying webview as an inline component? .  Could you please provide a example if it supports. For eg: Displaying as one of the child widget in a clolumn widget.

**Comment by luis901101** [comment]
Yeah it does. Both **OauthWebView** and **BaseWebView** are widgets so you can use it in any widget tree. In fact that's what is done in the [**OAuthWebScreen**](https://github.com/luis901101/oauth_webauth/blob/master/lib/src/oauth_web_screen.dart) and [**BaseWebScreen**](https://github.com/luis901101/oauth_webauth/blob/master/lib/src/base_web_screen.dart) respectively.
You can check example project, or check the plugin code to see further.
